In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("full_data_dump_8B.csv")

In [3]:
from llm_bridge import LLMBridge

In [ ]:
bridge = LLMBridge(
        model="gpt-5.4-2026-03-05",
        system="You are a concise science communicator.",
        temperature=0.5
    )

In [43]:
print(bridge)

LLMBridge(model='gpt-5.4-2026-03-05', temperature=0.5, max_tokens=None)

In [44]:
# Load the prompt template
with open("prompt.txt", "r") as f:
    prompt_template = f.read()

# Create batch of prompts and map each prompt to its query_id
batch_prompts = []
ids = []

for _, row in df.iterrows():
    prompt = prompt_template.replace("{QUERY}", row["query"])
    batch_prompts.append(prompt)
    ids.append(row["id"])
    
# Display the count
print(f"Created {len(batch_prompts)} prompts")
print(f"Created mapping for {len(ids)} prompt->query_id")

Created 280 prompts
Created mapping for 280 prompt->query_id

In [45]:
print(ids[0])

6517

In [46]:
answers = bridge.ask_llm_batch(batch_prompts)

[LLMBridge] Batch submitted — id: batch_69c627f736548190b7663a519b623ff0  (280 requests, model: gpt-5.4-2026-03-05)
[LLMBridge] Batch batch_69c627f736548190b7663a519b623ff0 status: validating
[LLMBridge] Batch batch_69c627f736548190b7663a519b623ff0 status: validating
[LLMBridge] Batch batch_69c627f736548190b7663a519b623ff0 status: validating
[LLMBridge] Batch batch_69c627f736548190b7663a519b623ff0 status: in_progress
[LLMBridge] Batch batch_69c627f736548190b7663a519b623ff0 status: in_progress
[LLMBridge] Batch batch_69c627f736548190b7663a519b623ff0 status: in_progress
[LLMBridge] Batch batch_69c627f736548190b7663a519b623ff0 status: in_progress
[LLMBridge] Batch batch_69c627f736548190b7663a519b623ff0 status: in_progress
[LLMBridge] Batch batch_69c627f736548190b7663a519b623ff0 status: finalizing
[LLMBridge] Batch batch_69c627f736548190b7663a519b623ff0 status: finalizing
[LLMBridge] Batch batch_69c627f736548190b7663a519b623ff0 status: completed

In [49]:
for id_, a in zip(ids, answers):
    df.loc[df["id"] == id_, "response"] = a

In [51]:
df.head()

,deconstructed_facts,entities,final_candidates,ground_truths,grounding_candidates,id,initial_symbol_candidates,query,relations,results,status,step2_entities_response,step3_relation_response,step3_relation_validation_response,vss_merged_candidates,response
0,Target: The ANSWER is a cell structure.\nFact ...,"{""ANSWER"": {""type"": [""cellular_component""], ""l...","{""A"": [""CandidateContext(\n node_id=17434,\n ...","[56241, 55842, 56174, 56263]","[56241, 56263, 55517, 126873, 56073, 56436, 55...",6517,"{""A"": [""CandidateContext(\n node_id=17434,\n ...",Which cell structures are involved in interact...,"{('ANSWER', 'B'): ['interacts with'], ('B', 'A...","{""answer_list"": [56241, 56263, 55517, 126873, ...",SUCCESS,"{\n ""ANSWER"": {\n ""name"": ""cell stru...","[\n (""ANSWER"", ""B"", ""interacts with""),\n (""B...","[(""ANSWER"", ""B"", ""interacts with""), (""B"", ""A"",...","[56241, 56263, 55517, 126873, 56073, 56436, 55...",ID: 22
1,Target: The ANSWER is a gene/protein.\nFact 1:...,"{""ANSWER"": {""type"": [""gene/protein""], ""lexical...","{""A"": [""CandidateContext(\n node_id=64835,\n ...",[10833],"[61, 2773, 3387, 1403, 1532, 2500, 13628, 704,...",9996,"{""A"": [""CandidateContext(\n node_id=64835,\n ...",Which genes or proteins are expressed exclusiv...,"{('ANSWER', 'A'): ['expression present'], ('AN...","{""answer_list"": [61, 2773, 3387, 1403, 1532, 2...",SUCCESS,"{\n ""ANSWER"": {\n ""name"": ""gene/prot...","[\n (""ANSWER"", ""A"", ""expression present""),\n ...","[(""ANSWER"", ""A"", ""expression present""), (""ANSW...","[61, 2773, 3387, 1403, 1532, 2500, 13628, 704,...",ID: 3
2,Target: The ANSWER is a medication.\nFact 1: T...,"{""ANSWER"": {""type"": [""drug""], ""lexical"": {""nam...","{""A"": [""CandidateContext(\n node_id=14609,\n ...",[15179],"[14880, 20293, 15179, 15885, 20497, 14132, 147...",3630,"{""A"": [""CandidateContext(\n node_id=14609,\n ...",Could you suggest any medications effective fo...,"{('ANSWER', 'A'): ['off-label use'], ('ANSWER'...","{""answer_list"": [14880, 20293, 15179, 15885, 2...",SUCCESS,"{\n ""ANSWER"": {\n ""name"": ""medicatio...","[\n (""ANSWER"", ""B"", ""indication""),\n (""ANSWE...","[('ANSWER', 'B', 'indication'), ('ANSWER', 'A'...","[14880, 20293, 15179, 15885, 20497, 14132, 147...",ID: 13
3,Target: The ANSWER is a gene/protein.\nFact 1:...,"{""ANSWER"": {""type"": [""gene/protein""], ""lexical...","{""A"": [""CandidateContext(\n node_id=1687,\n ...","[43, 2140]","[4238, 1687, 301, 443, 10225, 6985, 13070, 572...",10252,"{""A"": [""CandidateContext(\n node_id=1687,\n ...",Which gene or protein responsible for coding t...,"{('ANSWER', 'C'): ['ppi'], ('C', 'B'): ['inter...","{""answer_list"": [4238, 1687, 301, 443, 10225, ...",SUCCESS,"{\n ""ANSWER"": {\n ""name"": ""gene/prot...","[\n (""ANSWER"", ""C"", ""ppi""),\n (""ANSWER"", ""C""...","[\n (""ANSWER"", ""C"", ""ppi""),\n (""C"", ""B"", ""in...","[4238, 1687, 301, 443, 10225, 6985, 13070, 572...",ID: 17
4,Target: The ANSWER is an autosomal dominant di...,"{""ANSWER"": {""type"": [""disease""], ""lexical"": {""...","{""A"": [""CandidateContext(\n node_id=65855,\n ...",[30638],NaN,5142,"{""A"": [""CandidateContext(\n node_id=65855,\n ...",Which autosomal dominant diseases are linked t...,"{('B', 'A'): ['linked to'], ('ANSWER', 'B'): [...","{""answer_set"": ""set()"", ""ground_truth_set"": ""{...",SUCCESS,"{\n ""ANSWER"": {\n ""name"": ""autosomal...","[\n (""ANSWER"", ""B"", ""linked to""),\n (""B"", ""A...","[(""B"", ""A"", ""linked to""), (""ANSWER"", ""B"", ""lin...","[38395, 30638, 32617, 38422, 29485, 30770, 381...",ID: 14

In [59]:
df.to_csv("with_template_id.csv")

In [55]:
df["template_id"] = df["response"].str.extract(r"(\d+)").astype(int)

In [56]:
df["template_id"]

0      22
1       3
2      13
3      17
4      14
       ..
275    17
276     0
277     1
278     5
279    14
Name: template_id, Length: 280, dtype: int64

In [58]:
len(df[df["template_id"]==0])

85

In [60]:
template_df  = pd.read_csv("prime_templates.csv")

In [61]:
template_df.head()

,Id,Template,No_of_hops,No_of_entities,Entities,No_of_relations,relations
0,1,(effect/phenotype → [phenotype absent] → disea...,1,3,"effect/phenotype, disease, drug",2,"phenotype_absent, contraindication"
1,2,(drug → [contraindication] → disease ← [associ...,1,3,"gene/protein, disease, drug",2,"associated_with, contraindication"
2,3,(anatomy → [expression present] → gene/protein...,1,2,"gene/protein, anatomy",2,"expression_present, expression_absent"
3,4,(anatomy → [expression absent] → gene/protein ...,1,2,"anatomy, gene/protein",2,"expression_present, expression_absent"
4,5,(drug → [carrier] → gene/protein ← [carrier] ←...,1,2,drug. gene/protein,1,carrier

In [62]:
new_df = pd.DataFrame()

In [63]:
new_df["id"] = df["id"]

In [64]:
new_df["query"] = df["query"]

In [65]:
new_df["org_entities"]=df["entities"]

In [66]:
new_df["org_relations"]=df["relations"]

In [67]:
new_df["results"]=df["results"]

In [68]:
new_df["answer_list"]=df["vss_merged_candidates"]

In [94]:
new_df["ground_truths"]=df["ground_truths"]

In [69]:
import ast

In [71]:
new_df["results"]=new_df["results"].map(lambda x: ast.literal_eval(x))

In [74]:
new_df["retrieved_answer_list"] = new_df["results"].map(lambda x: x.get('answer_list', []))

In [77]:
new_df["retrieved_metrics"] = new_df["results"].map(lambda x: x["metrics"])

In [78]:
new_df["template_id"]=df["template_id"]

In [79]:
new_df.to_csv("anaylsis_dump_8B.csv")

In [120]:
merged_df = new_df.merge(
    template_df,
    left_on="template_id",
    right_on="Id",
    how="left"   # keeps all rows from new_df
)

In [121]:
merged_df.head()

,id,query,org_entities,org_relations,results,answer_list,retrieved_answer_list,retrieved_metrics,template_id,ground_truths,Id,Template,No_of_hops,No_of_entities,Entities,No_of_relations,relations
0,6517,Which cell structures are involved in interact...,"{""ANSWER"": {""type"": [""cellular_component""], ""l...","{('ANSWER', 'B'): ['interacts with'], ('B', 'A...","{'answer_list': [56241, 56263, 55517, 126873, ...","[56241, 56263, 55517, 126873, 56073, 56436, 55...","[56241, 56263, 55517, 126873, 56073, 56436, 55...","{'total_answers': 4, 'retrieved_count': 2, 'mi...",22,"[56241, 55842, 56174, 56263]",22.0,(drug → [target] → gene/protein → [interacts w...,2.0,3.0,"drug, gene/protein, cellular_component",2.0,"target, interacts_with"
1,9996,Which genes or proteins are expressed exclusiv...,"{""ANSWER"": {""type"": [""gene/protein""], ""lexical...","{('ANSWER', 'A'): ['expression present'], ('AN...","{'answer_list': [61, 2773, 3387, 1403, 1532, 2...","[61, 2773, 3387, 1403, 1532, 2500, 13628, 704,...","[61, 2773, 3387, 1403, 1532, 2500, 13628, 704,...","{'total_answers': 1, 'retrieved_count': 1, 'mi...",3,[10833],3.0,(anatomy → [expression present] → gene/protein...,1.0,2.0,"gene/protein, anatomy",2.0,"expression_present, expression_absent"
2,3630,Could you suggest any medications effective fo...,"{""ANSWER"": {""type"": [""drug""], ""lexical"": {""nam...","{('ANSWER', 'A'): ['off-label use'], ('ANSWER'...","{'answer_list': [14880, 20293, 15179, 15885, 2...","[14880, 20293, 15179, 15885, 20497, 14132, 147...","[14880, 20293, 15179, 15885, 20497, 14132, 147...","{'total_answers': 1, 'retrieved_count': 1, 'mi...",13,[15179],13.0,(disease → [indication] → drug → [contraindica...,2.0,2.0,"disease, drug",2.0,"indication, contraindication"
3,10252,Which gene or protein responsible for coding t...,"{""ANSWER"": {""type"": [""gene/protein""], ""lexical...","{('ANSWER', 'C'): ['ppi'], ('C', 'B'): ['inter...","{'answer_list': [4238, 1687, 301, 443, 10225, ...","[4238, 1687, 301, 443, 10225, 6985, 13070, 572...","[4238, 1687, 301, 443, 10225, 6985, 13070, 572...","{'total_answers': 2, 'retrieved_count': 0, 'mi...",17,"[43, 2140]",17.0,(pathway → [interacts with] → gene/protein → [...,2.0,2.0,"pathway, gene/protein",2.0,"interacts_with, ppi"
4,5142,Which autosomal dominant diseases are linked t...,"{""ANSWER"": {""type"": [""disease""], ""lexical"": {""...","{('B', 'A'): ['linked to'], ('ANSWER', 'B'): [...","{'answer_set': 'set()', 'ground_truth_set': '{...","[38395, 30638, 32617, 38422, 29485, 30770, 381...",[],"{'total_answers': 1, 'retrieved_count': 0, 'mi...",14,[30638],14.0,(disease → [parent-child] → disease → [phenoty...,2.0,2.0,"disease, effect/phenotype",2.0,"parent_child, phenotype_present"

In [117]:
merged_df = merged_df[merged_df["template_id"]!=0]

In [124]:
merged_df.to_csv("w_templ_analysis_dump_8B.csv", index=False)

In [91]:
from stark_qa import load_skb

WARNING: faiss must be imported for indexing

In [92]:
kb = load_skb("prime")

Loading from /home/payal-s/.cache/huggingface/hub/datasets--snap-stanford--stark/snapshots/88269e23e90587f99476c5dd74e235a0877e69be/skb/prime/processed!

In [122]:
def get_queries_one_by_one(df):
    subset = merged_df.loc[merged_df["template_id"] == 0, ["id", "query", "ground_truths"]]
    for _, row in subset.iterrows():
        yield row["id"], row["query"], row["ground_truths"]

gen = get_queries_one_by_one(merged_df)

In [123]:
# usage
id_, query, gt = next(gen)
print(id_, query, gt)

1755 Please find a metabolic process that either precedes or follows hyaluronan absorption and breakdown, and is involved in its metabolism or signaling cascades. [62592]

In [115]:
for i in [8034, 57603, 61258, 61259]:
    print(kb.get_doc_info(i, add_rel=True))

- name: GOLGA8G
- type: gene/protein
- source: NCBI
- details:
  - query: GOLGA8G
  - alias (other gene names): GOLGA8F
  - genomic_pos (genomic position): {'chr': '15', 'end': 28533014, 'ensemblgene': 'ENSG00000183629', 'start': 28519611, 'strand': -1}
  - name (gene name): golgin A8 family member G
  - summary (protein summary text): Predicted to be involved in Golgi organization. Predicted to be active in Golgi cis cisterna; Golgi cisterna membrane; and cis-Golgi network. [provided by Alliance of Genome Resources, Apr 2022]
- relations:
  ppi: {gene/protein: (MEOX2, USHBP1, TCF4, PDE4DIP, PPP2R1A, GOSR2, KCTD6, CDC5L, PDE4D, ATF4, STX11, SPAG5, BAAT, BEX3, ERP27, SSX2IP, MRFAP1, HDDC3, BEX5),}
  interacts_with: {cellular_component: (Golgi cisterna membrane, cis-Golgi network, Golgi cis cisterna),molecular_function: (protein binding),biological_process: (Golgi organization),}
  expression_present: {anatomy: (testis),}
- name: GOLGA8O
- type: gene/protein
- source: NCBI
- details:
  - query: GOLGA8O
  - genomic_pos (genomic position): {'chr': '15', 'end': 30565684, 'ensemblgene': 'ENSG00000178115', 'start': 30552050, 'strand': 1}
  - name (gene name): golgin A8 family member O
  - summary (protein summary text): Predicted to be involved in Golgi organization. Predicted to be located in Golgi apparatus. Predicted to be active in Golgi cis cisterna; Golgi cisterna membrane; and cis-Golgi network. [provided by Alliance of Genome Resources, Apr 2022]
- relations:
  interacts_with: {cellular_component: (Golgi cisterna membrane, cis-Golgi network, Golgi cis cisterna),molecular_function: (protein binding),biological_process: (Golgi organization),}
  expression_present: {anatomy: (testis, cerebral cortex, esophagus, skeletal muscle tissue, tibial nerve, frontal cortex, thyroid gland, heart left ventricle, multi-cellular organism, female gonad),}
- name: GOLGA8N
- type: gene/protein
- source: NCBI
- details:
  - query: GOLGA8N
  - alias (other gene names): GOLGA8R
  - genomic_pos (genomic position): {'chr': '15', 'end': 32607310, 'ensemblgene': 'ENSG00000232653', 'start': 32593456, 'strand': 1}
  - name (gene name): golgin A8 family member N
  - summary (protein summary text): Predicted to be involved in Golgi organization. Predicted to be located in Golgi apparatus. Predicted to be active in Golgi cis cisterna; Golgi cisterna membrane; and cis-Golgi network. [provided by Alliance of Genome Resources, Apr 2022]
- relations:
  interacts_with: {cellular_component: (Golgi cisterna membrane, cis-Golgi network, Golgi cis cisterna),biological_process: (Golgi organization),}
  expression_present: {anatomy: (zone of skin, lymph node, adult mammalian kidney, intestine, blood, prefrontal cortex, testis, stomach, heart, brain, cerebral cortex, adipose tissue, esophagus, saliva-secreting gland, skeletal muscle tissue, colon, cortex of kidney, urinary bladder, pancreas, endometrium, myometrium, tibial nerve, muscle of leg, frontal cortex, temporal lobe, placenta, cerebellum, thyroid gland, lung, heart left ventricle, spleen, liver, small intestine, kidney, cerebellar cortex, prostate gland, adrenal gland, muscle tissue, fallopian tube, thoracic mammary gland, dorsolateral prefrontal cortex, multi-cellular organism, female gonad),}
- name: GOLGA8S
- type: gene/protein
- source: NCBI
- details:
  - query: GOLGA8S
  - genomic_pos (genomic position): {'chr': '15', 'end': 23368341, 'ensemblgene': 'ENSG00000261739', 'start': 23354748, 'strand': 1}
  - name (gene name): golgin A8 family member S
  - summary (protein summary text): Predicted to be involved in Golgi organization. Predicted to be active in Golgi cis cisterna; Golgi cisterna membrane; and cis-Golgi network. [provided by Alliance of Genome Resources, Apr 2022]
- relations:
  interacts_with: {cellular_component: (Golgi cisterna membrane, cis-Golgi network, Golgi cis cisterna),biological_process: (Golgi organization),}
  expression_present: {anatomy: (prefrontal cortex, testis, cerebral cortex, adipose tissue, pancreas, endometrium, frontal cortex, thyroid gland, dorsolateral prefrontal cortex),}

In [ ]:
print(kb.get_neighbor_nodes(62, "parent-child"))

[62418, 128127, 128128]

In [116]:
new_df[new_df["id"]==4438]["template_id"]=23

In [104]:
for i in [62418, 128127, 128128]:
    print(kb.get_doc_info(i, add_rel=True))

- name: Glycosaminoglycan metabolism
- type: pathway
- source: REACTOME
- details:
  - dbId: 1630316
  - displayName: Glycosaminoglycan metabolism
  - stId: R-HSA-1630316
  - stIdVersion: R-HSA-1630316.3
  - isInDisease: False
  - isInferred: False
  - name: ['Glycosaminoglycan metabolism']
  - releaseDate: 2012-06-12
  - speciesName: Homo sapiens
  - goBiologicalProcess: {'dbId': 3777, 'displayName': 'glycosaminoglycan metabolic process', 'accession': '0030203', 'databaseName': 'GO', 'definition': 'The chemical reactions and pathways involving glycosaminoglycans, any of a group of polysaccharides that contain amino sugars.', 'name': 'glycosaminoglycan metabolic process', 'url': 'https://www.ebi.ac.uk/QuickGO/term/GO:0030203', 'className': 'GO_BiologicalProcess', 'schemaClass': 'GO_BiologicalProcess'}
  - literatureReference: [{'dbId': 1638021, 'displayName': 'Proteoglycans and Sulfated Glycosaminoglycans', 'title': 'Proteoglycans and Sulfated Glycosaminoglycans', 'year': 2009, 'className': 'Book', 'schemaClass': 'Book'}, {'dbId': 1638022, 'displayName': 'The mucopolysaccharidoses: a success of molecular medicine', 'title': 'The mucopolysaccharidoses: a success of molecular medicine', 'journal': 'Expert Rev Mol Med', 'pages': 'e1', 'pubMedIdentifier': 18201392, 'volume': 10, 'year': 2008, 'url': 'http://www.ncbi.nlm.nih.gov/pubmed/18201392', 'className': 'LiteratureReference', 'schemaClass': 'LiteratureReference'}, {'dbId': 1638020, 'displayName': 'The mucopolysaccharidoses: inborn errors of glycosaminoglycan catabolism', 'title': 'The mucopolysaccharidoses: inborn errors of glycosaminoglycan catabolism', 'journal': 'Hum Genet', 'pages': '233-55', 'pubMedIdentifier': 820626, 'volume': 32, 'year': 1976, 'url': 'http://www.ncbi.nlm.nih.gov/pubmed/820626', 'className': 'LiteratureReference', 'schemaClass': 'LiteratureReference'}]
  - orthologousEvent: [{'dbId': 9954185, 'displayName': 'Glycosaminoglycan metabolism', 'stId': 'R-MMU-1630316', 'stIdVersion': 'R-MMU-1630316.1', 'isInDisease': False, 'isInferred': True, 'name': ['Glycosaminoglycan metabolism'], 'releaseDate': '2023-09-13', 'speciesName': 'Mus musculus', 'inferredFrom': [1630316], 'hasDiagram': True, 'hasEHLD': False, 'className': 'Pathway', 'schemaClass': 'Pathway'}, {'dbId': 10064437, 'displayName': 'Glycosaminoglycan metabolism', 'stId': 'R-RNO-1630316', 'stIdVersion': 'R-RNO-1630316.1', 'isInDisease': False, 'isInferred': True, 'name': ['Glycosaminoglycan metabolism'], 'releaseDate': '2023-09-13', 'speciesName': 'Rattus norvegicus', 'inferredFrom': [1630316], 'hasDiagram': True, 'hasEHLD': False, 'className': 'Pathway', 'schemaClass': 'Pathway'}, {'dbId': 10167592, 'displayName': 'Glycosaminoglycan metabolism', 'stId': 'R-CFA-1630316', 'stIdVersion': 'R-CFA-1630316.1', 'isInDisease': False, 'isInferred': True, 'name': ['Glycosaminoglycan metabolism'], 'releaseDate': '2023-09-13', 'speciesName': 'Canis familiaris', 'inferredFrom': [1630316], 'hasDiagram': True, 'hasEHLD': False, 'className': 'Pathway', 'schemaClass': 'Pathway'}, {'dbId': 10277940, 'displayName': 'Glycosaminoglycan metabolism', 'stId': 'R-BTA-1630316', 'stIdVersion': 'R-BTA-1630316.1', 'isInDisease': False, 'isInferred': True, 'name': ['Glycosaminoglycan metabolism'], 'releaseDate': '2023-09-13', 'speciesName': 'Bos taurus', 'inferredFrom': [1630316], 'hasDiagram': True, 'hasEHLD': False, 'className': 'Pathway', 'schemaClass': 'Pathway'}, {'dbId': 10383619, 'displayName': 'Glycosaminoglycan metabolism', 'stId': 'R-SSC-1630316', 'stIdVersion': 'R-SSC-1630316.1', 'isInDisease': False, 'isInferred': True, 'name': ['Glycosaminoglycan metabolism'], 'releaseDate': '2023-09-13', 'speciesName': 'Sus scrofa', 'inferredFrom': [1630316], 'hasDiagram': True, 'hasEHLD': False, 'className': 'Pathway', 'schemaClass': 'Pathway'}, {'dbId': 10602863, 'displayName': 'Glycosaminoglycan metabolism', 'stId': 'R-XTR-1630316', 'stIdVersion': 'R-XTR-1630316.1', 'isInDisease': False, 'isInferred': True, 'name': ['Glycosaminoglycan metabolism'], 'releaseDate': '2023-09-13', 'speciesName': 'Xenopus tropicalis', 'inferredFrom': [1630316], 'hasDiagram': True, 'hasEHLD': False, 'className': 'Pathway', 'schemaClass': 'Pathway'}, {'dbId': 10696836, 'displayName': 'Glycosaminoglycan metabolism', 'stId': 'R-GGA-1630316', 'stIdVersion': 'R-GGA-1630316.1', 'isInDisease': False, 'isInferred': True, 'name': ['Glycosaminoglycan metabolism'], 'releaseDate': '2023-09-13', 'speciesName': 'Gallus gallus', 'inferredFrom': [1630316], 'hasDiagram': True, 'hasEHLD': False, 'className': 'Pathway', 'schemaClass': 'Pathway'}, {'dbId': 10778947, 'displayName': 'Glycosaminoglycan metabolism', 'stId': 'R-DME-1630316', 'stIdVersion': 'R-DME-1630316.1', 'isInDisease': False, 'isInferred': True, 'name': ['Glycosaminoglycan metabolism'], 'releaseDate': '2023-09-13', 'speciesName': 'Drosophila melanogaster', 'inferredFrom': [1630316], 'hasDiagram': True, 'hasEHLD': False, 'className': 'Pathway', 'schemaClass': 'Pathway'}, {'dbId': 10856162, 'displayName': 'Glycosaminoglycan metabolism', 'stId': 'R-CEL-1630316', 'stIdVersion': 'R-CEL-1630316.1', 'isInDisease': False, 'isInferred': True, 'name': ['Glycosaminoglycan metabolism'], 'releaseDate': '2023-09-13', 'speciesName': 'Caenorhabditis elegans', 'inferredFrom': [1630316], 'hasDiagram': True, 'hasEHLD': False, 'className': 'Pathway', 'schemaClass': 'Pathway'}, {'dbId': 10906190, 'displayName': 'Glycosaminoglycan metabolism', 'stId': 'R-DDI-1630316', 'stIdVersion': 'R-DDI-1630316.1', 'isInDisease': False, 'isInferred': True, 'name': ['Glycosaminoglycan metabolism'], 'releaseDate': '2023-09-13', 'speciesName': 'Dictyostelium discoideum', 'inferredFrom': [1630316], 'hasDiagram': True, 'hasEHLD': False, 'className': 'Pathway', 'schemaClass': 'Pathway'}, {'dbId': 10933334, 'displayName': 'Glycosaminoglycan metabolism', 'stId': 'R-SPO-1630316', 'stIdVersion': 'R-SPO-1630316.1', 'isInDisease': False, 'isInferred': True, 'name': ['Glycosaminoglycan metabolism'], 'releaseDate': '2023-09-13', 'speciesName': 'Schizosaccharomyces pombe', 'inferredFrom': [1630316], 'hasDiagram': True, 'hasEHLD': False, 'className': 'Pathway', 'schemaClass': 'Pathway'}, {'dbId': 10960506, 'displayName': 'Glycosaminoglycan metabolism', 'stId': 'R-SCE-1630316', 'stIdVersion': 'R-SCE-1630316.1', 'isInDisease': False, 'isInferred': True, 'name': ['Glycosaminoglycan metabolism'], 'releaseDate': '2023-09-13', 'speciesName': 'Saccharomyces cerevisiae', 'inferredFrom': [1630316], 'hasDiagram': True, 'hasEHLD': False, 'className': 'Pathway', 'schemaClass': 'Pathway'}, {'dbId': 10503743, 'displayName': 'Glycosaminoglycan metabolism', 'stId': 'R-DRE-1630316', 'stIdVersion': 'R-DRE-1630316.1', 'isInDisease': False, 'isInferred': True, 'name': ['Glycosaminoglycan metabolism'], 'releaseDate': '2023-09-13', 'speciesName': 'Danio rerio', 'inferredFrom': [1630316], 'hasDiagram': True, 'hasEHLD': False, 'className': 'Pathway', 'schemaClass': 'Pathway'}]
  - species: [{'dbId': 48887, 'displayName': 'Homo sapiens', 'name': ['Homo sapiens', 'H. sapiens', 'Hs', 'human', 'man'], 'taxId': '9606', 'abbreviation': 'HSA', 'className': 'Species', 'schemaClass': 'Species'}]
  - summation: [{'dbId': 1636575, 'displayName': 'Glycosaminoglycans (GAGs) are long, unbranched polysaccharid...', 'text': 'Glycosaminoglycans (GAGs) are long, unbranched polysaccharides containing a repeating disaccharide unit composed of a hexosamine (either N-acetylgalactosamine (GalNAc) or N-acetylglucosamine (GlcNAc)) and a uronic acid (glucuronate or iduronate). They can be heavily sulfated. GAGs are located primarily in the extracellular matrix (ECM) and on cell membranes, acting as a lubricating fluid for joints and as part of signalling processes. They have structural roles in connective tissue, cartilage, bone and blood vessels (Esko et al. 2009). GAGs are degraded in the lysosome as part of their natural turnover. Defects in the lysosomal enzymes responsible for the metabolism of membrane-associated GAGs lead to lysosomal storage diseases called mucopolysaccharidoses (MPS). MPSs are characterised by the accumulation of GAGs in lysosomes resulting in chronic, progressively debilitating disorders that in many instances lead to severe psychomotor retardation and premature death (Cantz & Gehler 1976, Clarke 2008). The biosynthesis and breakdown of the main GAGs (hyaluronate, keratan sulfate, chondroitin sulfate, dermatan sulfate and heparan sulfate) is described here.', 'className': 'Summation', 'schemaClass': 'Summation'}]
  - reviewStatus: {'dbId': 9821382, 'displayName': 'five stars', 'definition': 'externally reviewed', 'name': ['five stars'], 'className': 'ReviewStatus', 'schemaClass': 'ReviewStatus'}
  - doi: 10.3180/REACT_121315.1
  - hasDiagram: True
  - hasEHLD: False
  - hasEvent: [{'dbId': 2142845, 'displayName': 'Hyaluronan metabolism', 'stId': 'R-HSA-2142845', 'stIdVersion': 'R-HSA-2142845.2', 'isInDisease': False, 'isInferred': False, 'name': ['Hyaluronan metabolism'], 'releaseDate': '2012-06-12', 'speciesName': 'Homo sapiens', 'hasDiagram': False, 'hasEHLD': False, 'className': 'Pathway', 'schemaClass': 'Pathway'}, {'dbId': 174362, 'displayName': 'Transport and synthesis of PAPS', 'stId': 'R-HSA-174362', 'stIdVersion': 'R-HSA-174362.5', 'isInDisease': False, 'isInferred': False, 'name': ['Transport and synthesis of PAPS'], 'releaseDate': '2006-04-24', 'speciesName': 'Homo sapiens', 'doi': '10.3180/R-HSA-174362.3', 'hasDiagram': False, 'hasEHLD': False, 'className': 'Pathway', 'schemaClass': 'Pathway'}, {'dbId': 1638074, 'displayName': 'Keratan sulfate/keratin metabolism', 'stId': 'R-HSA-1638074', 'stIdVersion': 'R-HSA-1638074.2', 'isInDisease': False, 'isInferred': False, 'name': ['Keratan sulfate/keratin metabolism'], 'releaseDate': '2012-06-12', 'speciesName': 'Homo sapiens', 'hasDiagram': False, 'hasEHLD': False, 'className': 'Pathway', 'schemaClass': 'Pathway'}, {'dbId': 1638091, 'displayName': 'Heparan sulfate/heparin (HS-GAG) metabolism', 'stId': 'R-HSA-1638091', 'stIdVersion': 'R-HSA-1638091.2', 'isInDisease': False, 'isInferred': False, 'name': ['Heparan sulfate/heparin (HS-GAG) metabolism'], 'releaseDate': '2012-06-12', 'speciesName': 'Homo sapiens', 'hasDiagram': False, 'hasEHLD': False, 'className': 'Pathway', 'schemaClass': 'Pathway'}, {'dbId': 1793185, 'displayName': 'Chondroitin sulfate/dermatan sulfate metabolism', 'stId': 'R-HSA-1793185', 'stIdVersion': 'R-HSA-1793185.2', 'isInDisease': False, 'isInferred': False, 'name': ['Chondroitin sulfate/dermatan sulfate metabolism'], 'releaseDate': '2012-06-12', 'speciesName': 'Homo sapiens', 'hasDiagram': False, 'hasEHLD': False, 'className': 'Pathway', 'schemaClass': 'Pathway'}]
  - className: Pathway
  - schemaClass: Pathway
- relations:
  parent-child: {pathway: (Keratan sulfate/keratin metabolism, Heparan sulfate/heparin (HS-GAG) metabolism, Chondroitin sulfate/dermatan sulfate metabolism, Hyaluronan metabolism, Metabolism of carbohydrates, Transport and synthesis of PAPS),}
- name: Hyaluronan biosynthesis and export
- type: pathway
- source: REACTOME
- details:
  - dbId: 2142850
  - displayName: Hyaluronan biosynthesis and export
  - stId: R-HSA-2142850
  - stIdVersion: R-HSA-2142850.3
  - isInDisease: False
  - isInferred: False
  - name: ['Hyaluronan biosynthesis and export']
  - releaseDate: 2012-06-12
  - speciesName: Homo sapiens
  - goBiologicalProcess: {'dbId': 21628, 'displayName': 'hyaluronan biosynthetic process', 'accession': '0030213', 'databaseName': 'GO', 'definition': 'The chemical reactions and pathways resulting in the formation of hyaluronan, the naturally occurring anionic form of hyaluronic acid, any member of a group of glycosaminoglycans, the repeat units of which consist of beta-1,4 linked D-glucuronyl-beta-(1,3)-N-acetyl-D-glucosamine.', 'name': 'hyaluronan biosynthetic process', 'url': 'https://www.ebi.ac.uk/QuickGO/term/GO:0030213', 'className': 'GO_BiologicalProcess', 'schemaClass': 'GO_BiologicalProcess'}
  - literatureReference: [{'dbId': 2142873, 'displayName': 'Biochemistry of hyaluronan', 'title': 'Biochemistry of hyaluronan', 'journal': 'Acta Otolaryngol Suppl', 'pages': '7-24', 'pubMedIdentifier': 3124495, 'volume': 442, 'year': 1987, 'url': 'http://www.ncbi.nlm.nih.gov/pubmed/3124495', 'className': 'LiteratureReference', 'schemaClass': 'LiteratureReference'}, {'dbId': 2142869, 'displayName': 'Hyaluronan synthases: a decade-plus of novel glycosyltransferases', 'title': 'Hyaluronan synthases: a decade-plus of novel glycosyltransferases', 'journal': 'J Biol Chem', 'pages': '36777-81', 'pubMedIdentifier': 17981795, 'volume': 282, 'year': 2007, 'url': 'http://www.ncbi.nlm.nih.gov/pubmed/17981795', 'className': 'LiteratureReference', 'schemaClass': 'LiteratureReference'}]
  - orthologousEvent: [{'dbId': 10505099, 'displayName': 'Hyaluronan biosynthesis and export', 'stId': 'R-DRE-2142850', 'stIdVersion': 'R-DRE-2142850.1', 'isInDisease': False, 'isInferred': True, 'name': ['Hyaluronan biosynthesis and export'], 'releaseDate': '2023-09-13', 'speciesName': 'Danio rerio', 'inferredFrom': [2142850], 'hasDiagram': False, 'hasEHLD': False, 'className': 'Pathway', 'schemaClass': 'Pathway'}, {'dbId': 10906486, 'displayName': 'Hyaluronan biosynthesis and export', 'stId': 'R-DDI-2142850', 'stIdVersion': 'R-DDI-2142850.1', 'isInDisease': False, 'isInferred': True, 'name': ['Hyaluronan biosynthesis and export'], 'releaseDate': '2023-09-13', 'speciesName': 'Dictyostelium discoideum', 'inferredFrom': [2142850], 'hasDiagram': False, 'hasEHLD': False, 'className': 'Pathway', 'schemaClass': 'Pathway'}, {'dbId': 10857126, 'displayName': 'Hyaluronan biosynthesis and export', 'stId': 'R-CEL-2142850', 'stIdVersion': 'R-CEL-2142850.1', 'isInDisease': False, 'isInferred': True, 'name': ['Hyaluronan biosynthesis and export'], 'releaseDate': '2023-09-13', 'speciesName': 'Caenorhabditis elegans', 'inferredFrom': [2142850], 'hasDiagram': False, 'hasEHLD': False, 'className': 'Pathway', 'schemaClass': 'Pathway'}, {'dbId': 10698148, 'displayName': 'Hyaluronan biosynthesis and export', 'stId': 'R-GGA-2142850', 'stIdVersion': 'R-GGA-2142850.1', 'isInDisease': False, 'isInferred': True, 'name': ['Hyaluronan biosynthesis and export'], 'releaseDate': '2023-09-13', 'speciesName': 'Gallus gallus', 'inferredFrom': [2142850], 'hasDiagram': False, 'hasEHLD': False, 'className': 'Pathway', 'schemaClass': 'Pathway'}, {'dbId': 10604125, 'displayName': 'Hyaluronan biosynthesis and export', 'stId': 'R-XTR-2142850', 'stIdVersion': 'R-XTR-2142850.1', 'isInDisease': False, 'isInferred': True, 'name': ['Hyaluronan biosynthesis and export'], 'releaseDate': '2023-09-13', 'speciesName': 'Xenopus tropicalis', 'inferredFrom': [2142850], 'hasDiagram': False, 'hasEHLD': False, 'className': 'Pathway', 'schemaClass': 'Pathway'}, {'dbId': 10384957, 'displayName': 'Hyaluronan biosynthesis and export', 'stId': 'R-SSC-2142850', 'stIdVersion': 'R-SSC-2142850.1', 'isInDisease': False, 'isInferred': True, 'name': ['Hyaluronan biosynthesis and export'], 'releaseDate': '2023-09-13', 'speciesName': 'Sus scrofa', 'inferredFrom': [2142850], 'hasDiagram': False, 'hasEHLD': False, 'className': 'Pathway', 'schemaClass': 'Pathway'}, {'dbId': 10279288, 'displayName': 'Hyaluronan biosynthesis and export', 'stId': 'R-BTA-2142850', 'stIdVersion': 'R-BTA-2142850.1', 'isInDisease': False, 'isInferred': True, 'name': ['Hyaluronan biosynthesis and export'], 'releaseDate': '2023-09-13', 'speciesName': 'Bos taurus', 'inferredFrom': [2142850], 'hasDiagram': False, 'hasEHLD': False, 'className': 'Pathway', 'schemaClass': 'Pathway'}, {'dbId': 10168930, 'displayName': 'Hyaluronan biosynthesis and export', 'stId': 'R-CFA-2142850', 'stIdVersion': 'R-CFA-2142850.1', 'isInDisease': False, 'isInferred': True, 'name': ['Hyaluronan biosynthesis and export'], 'releaseDate': '2023-09-13', 'speciesName': 'Canis familiaris', 'inferredFrom': [2142850], 'hasDiagram': False, 'hasEHLD': False, 'className': 'Pathway', 'schemaClass': 'Pathway'}, {'dbId': 10065795, 'displayName': 'Hyaluronan biosynthesis and export', 'stId': 'R-RNO-2142850', 'stIdVersion': 'R-RNO-2142850.1', 'isInDisease': False, 'isInferred': True, 'name': ['Hyaluronan biosynthesis and export'], 'releaseDate': '2023-09-13', 'speciesName': 'Rattus norvegicus', 'inferredFrom': [2142850], 'hasDiagram': False, 'hasEHLD': False, 'className': 'Pathway', 'schemaClass': 'Pathway'}, {'dbId': 9955557, 'displayName': 'Hyaluronan biosynthesis and export', 'stId': 'R-MMU-2142850', 'stIdVersion': 'R-MMU-2142850.1', 'isInDisease': False, 'isInferred': True, 'name': ['Hyaluronan biosynthesis and export'], 'releaseDate': '2023-09-13', 'speciesName': 'Mus musculus', 'inferredFrom': [2142850], 'hasDiagram': False, 'hasEHLD': False, 'className': 'Pathway', 'schemaClass': 'Pathway'}]
  - species: [{'dbId': 48887, 'displayName': 'Homo sapiens', 'name': ['Homo sapiens', 'H. sapiens', 'Hs', 'human', 'man'], 'taxId': '9606', 'abbreviation': 'HSA', 'className': 'Species', 'schemaClass': 'Species'}]
  - summation: [{'dbId': 2142882, 'displayName': 'Hyaluronan (hyaluronic acid, HA) is composed of repeating di...', 'text': 'Hyaluronan (hyaluronic acid, HA) is composed of repeating disaccharide units of glucuronic acid and N-acetylglucosamine [-4GlcAb1-3GlcNAcb1-]. It is synthesized in the cell membrane by adding monosaccharides to the reducing end of the chain using the precursors UDP-glucuronic acid and UDP-N-acetylglucosamine in the presence of Mg2+. The integral membrane dual-action glycosyltransferase proteins hyaluronan synthases, of which vertebrates have three types (HAS1-3), catalyze these monosaccharide additions. Unlike other GAGs, HA is synthesized as a free glycan, not attached to a protein (Laurent 1987, Weigel & DeAngelis, 2007). As HA is synthesised it is extruded from the cell by an ABC-type transporter into the extracellular medium.', 'className': 'Summation', 'schemaClass': 'Summation'}]
  - reviewStatus: {'dbId': 9821382, 'displayName': 'five stars', 'definition': 'externally reviewed', 'name': ['five stars'], 'className': 'ReviewStatus', 'schemaClass': 'ReviewStatus'}
  - hasDiagram: False
  - hasEHLD: False
  - hasEvent: [{'dbId': 2160851, 'displayName': 'HAS1,2,3 mediate the polymerization of HA', 'stId': 'R-HSA-2160851', 'stIdVersion': 'R-HSA-2160851.3', 'isInDisease': False, 'isInferred': False, 'name': ['HAS1,2,3 mediate the polymerization of HA'], 'releaseDate': '2012-06-12', 'speciesName': 'Homo sapiens', 'isChimeric': False, 'category': 'transition', 'className': 'Reaction', 'schemaClass': 'Polymerisation'}, {'dbId': 2142859, 'displayName': 'Growing HA is extruded from the cell by ABCC5', 'stId': 'R-HSA-2142859', 'stIdVersion': 'R-HSA-2142859.2', 'isInDisease': False, 'isInferred': False, 'name': ['Growing HA is extruded from the cell by ABCC5'], 'releaseDate': '2012-06-12', 'speciesName': 'Homo sapiens', 'isChimeric': False, 'category': 'transition', 'className': 'Reaction', 'schemaClass': 'Reaction'}, {'dbId': 5693356, 'displayName': 'CEMIP hydrolyses HA', 'stId': 'R-HSA-5693356', 'stIdVersion': 'R-HSA-5693356.2', 'isInDisease': False, 'isInferred': False, 'name': ['CEMIP hydrolyses HA'], 'releaseDate': '2015-09-22', 'speciesName': 'Homo sapiens', 'isChimeric': False, 'category': 'transition', 'className': 'Reaction', 'schemaClass': 'Reaction'}]
  - className: Pathway
  - schemaClass: Pathway
- relations:
  parent-child: {pathway: (Hyaluronan metabolism),}
  interacts_with: {gene/protein: (HAS2, HAS3, HAS1, ABCC5, CEMIP),}
- name: Hyaluronan uptake and degradation
- type: pathway
- source: REACTOME
- details:
  - dbId: 2160916
  - displayName: Hyaluronan uptake and degradation
  - stId: R-HSA-2160916
  - stIdVersion: R-HSA-2160916.4
  - isInDisease: False
  - isInferred: False
  - name: ['Hyaluronan uptake and degradation']
  - releaseDate: 2012-06-12
  - speciesName: Homo sapiens

In [102]:
print(kb.get_doc_info(62592, add_rel=True))

- name: Hyaluronan metabolism
- type: pathway
- source: REACTOME
- details:
  - dbId: 2142845
  - displayName: Hyaluronan metabolism
  - stId: R-HSA-2142845
  - stIdVersion: R-HSA-2142845.2
  - isInDisease: False
  - isInferred: False
  - name: ['Hyaluronan metabolism']
  - releaseDate: 2012-06-12
  - speciesName: Homo sapiens
  - goBiologicalProcess: {'dbId': 21627, 'displayName': 'hyaluronan metabolic process', 'accession': '0030212', 'databaseName': 'GO', 'definition': 'The chemical reactions and pathways involving hyaluronan, the naturally occurring anionic form of hyaluronic acid, any member of a group of glycosaminoglycans, the repeat units of which consist of beta-1,4 linked D-glucuronyl-beta-(1,3)-N-acetyl-D-glucosamine.', 'name': 'hyaluronan metabolic process', 'url': 'https://www.ebi.ac.uk/QuickGO/term/GO:0030212', 'className': 'GO_BiologicalProcess', 'schemaClass': 'GO_BiologicalProcess'}
  - literatureReference: [{'dbId': 2142843, 'displayName': 'Hyaluronan is not just a goo!', 'title': 'Hyaluronan is not just a goo!', 'journal': 'J Clin Invest', 'pages': '335-6', 'pubMedIdentifier': 10930435, 'volume': 106, 'year': 2000, 'url': 'http://www.ncbi.nlm.nih.gov/pubmed/10930435', 'className': 'LiteratureReference', 'schemaClass': 'LiteratureReference'}, {'dbId': 2142856, 'displayName': 'Hyaluronan: from extracellular glue to pericellular cue', 'title': 'Hyaluronan: from extracellular glue to pericellular cue', 'journal': 'Nat Rev Cancer', 'pages': '528-39', 'pubMedIdentifier': 15229478, 'volume': 4, 'year': 2004, 'url': 'http://www.ncbi.nlm.nih.gov/pubmed/15229478', 'className': 'LiteratureReference', 'schemaClass': 'LiteratureReference'}, {'dbId': 2142842, 'displayName': 'Role, metabolism, chemical modifications and applications of hyaluronan', 'title': 'Role, metabolism, chemical modifications and applications of hyaluronan', 'journal': 'Curr Med Chem', 'pages': '1718-45', 'pubMedIdentifier': 19442142, 'volume': 16, 'year': 2009, 'url': 'http://www.ncbi.nlm.nih.gov/pubmed/19442142', 'className': 'LiteratureReference', 'schemaClass': 'LiteratureReference'}]
  - orthologousEvent: [{'dbId': 10505101, 'displayName': 'Hyaluronan metabolism', 'stId': 'R-DRE-2142845', 'stIdVersion': 'R-DRE-2142845.1', 'isInDisease': False, 'isInferred': True, 'name': ['Hyaluronan metabolism'], 'releaseDate': '2023-09-13', 'speciesName': 'Danio rerio', 'inferredFrom': [2142845], 'hasDiagram': False, 'hasEHLD': False, 'className': 'Pathway', 'schemaClass': 'Pathway'}, {'dbId': 10906488, 'displayName': 'Hyaluronan metabolism', 'stId': 'R-DDI-2142845', 'stIdVersion': 'R-DDI-2142845.1', 'isInDisease': False, 'isInferred': True, 'name': ['Hyaluronan metabolism'], 'releaseDate': '2023-09-13', 'speciesName': 'Dictyostelium discoideum', 'inferredFrom': [2142845], 'hasDiagram': False, 'hasEHLD': False, 'className': 'Pathway', 'schemaClass': 'Pathway'}, {'dbId': 10857128, 'displayName': 'Hyaluronan metabolism', 'stId': 'R-CEL-2142845', 'stIdVersion': 'R-CEL-2142845.1', 'isInDisease': False, 'isInferred': True, 'name': ['Hyaluronan metabolism'], 'releaseDate': '2023-09-13', 'speciesName': 'Caenorhabditis elegans', 'inferredFrom': [2142845], 'hasDiagram': False, 'hasEHLD': False, 'className': 'Pathway', 'schemaClass': 'Pathway'}, {'dbId': 10780061, 'displayName': 'Hyaluronan metabolism', 'stId': 'R-DME-2142845', 'stIdVersion': 'R-DME-2142845.1', 'isInDisease': False, 'isInferred': True, 'name': ['Hyaluronan metabolism'], 'releaseDate': '2023-09-13', 'speciesName': 'Drosophila melanogaster', 'inferredFrom': [2142845], 'hasDiagram': False, 'hasEHLD': False, 'className': 'Pathway', 'schemaClass': 'Pathway'}, {'dbId': 10698150, 'displayName': 'Hyaluronan metabolism', 'stId': 'R-GGA-2142845', 'stIdVersion': 'R-GGA-2142845.1', 'isInDisease': False, 'isInferred': True, 'name': ['Hyaluronan metabolism'], 'releaseDate': '2023-09-13', 'speciesName': 'Gallus gallus', 'inferredFrom': [2142845], 'hasDiagram': False, 'hasEHLD': False, 'className': 'Pathway', 'schemaClass': 'Pathway'}, {'dbId': 10604127, 'displayName': 'Hyaluronan metabolism', 'stId': 'R-XTR-2142845', 'stIdVersion': 'R-XTR-2142845.1', 'isInDisease': False, 'isInferred': True, 'name': ['Hyaluronan metabolism'], 'releaseDate': '2023-09-13', 'speciesName': 'Xenopus tropicalis', 'inferredFrom': [2142845], 'hasDiagram': False, 'hasEHLD': False, 'className': 'Pathway', 'schemaClass': 'Pathway'}, {'dbId': 10384959, 'displayName': 'Hyaluronan metabolism', 'stId': 'R-SSC-2142845', 'stIdVersion': 'R-SSC-2142845.1', 'isInDisease': False, 'isInferred': True, 'name': ['Hyaluronan metabolism'], 'releaseDate': '2023-09-13', 'speciesName': 'Sus scrofa', 'inferredFrom': [2142845], 'hasDiagram': False, 'hasEHLD': False, 'className': 'Pathway', 'schemaClass': 'Pathway'}, {'dbId': 10279290, 'displayName': 'Hyaluronan metabolism', 'stId': 'R-BTA-2142845', 'stIdVersion': 'R-BTA-2142845.1', 'isInDisease': False, 'isInferred': True, 'name': ['Hyaluronan metabolism'], 'releaseDate': '2023-09-13', 'speciesName': 'Bos taurus', 'inferredFrom': [2142845], 'hasDiagram': False, 'hasEHLD': False, 'className': 'Pathway', 'schemaClass': 'Pathway'}, {'dbId': 10168932, 'displayName': 'Hyaluronan metabolism', 'stId': 'R-CFA-2142845', 'stIdVersion': 'R-CFA-2142845.1', 'isInDisease': False, 'isInferred': True, 'name': ['Hyaluronan metabolism'], 'releaseDate': '2023-09-13', 'speciesName': 'Canis familiaris', 'inferredFrom': [2142845], 'hasDiagram': False, 'hasEHLD': False, 'className': 'Pathway', 'schemaClass': 'Pathway'}, {'dbId': 10065797, 'displayName': 'Hyaluronan metabolism', 'stId': 'R-RNO-2142845', 'stIdVersion': 'R-RNO-2142845.1', 'isInDisease': False, 'isInferred': True, 'name': ['Hyaluronan metabolism'], 'releaseDate': '2023-09-13', 'speciesName': 'Rattus norvegicus', 'inferredFrom': [2142845], 'hasDiagram': False, 'hasEHLD': False, 'className': 'Pathway', 'schemaClass': 'Pathway'}, {'dbId': 9955559, 'displayName': 'Hyaluronan metabolism', 'stId': 'R-MMU-2142845', 'stIdVersion': 'R-MMU-2142845.1', 'isInDisease': False, 'isInferred': True, 'name': ['Hyaluronan metabolism'], 'releaseDate': '2023-09-13', 'speciesName': 'Mus musculus', 'inferredFrom': [2142845], 'hasDiagram': False, 'hasEHLD': False, 'className': 'Pathway', 'schemaClass': 'Pathway'}]
  - species: [{'dbId': 48887, 'displayName': 'Homo sapiens', 'name': ['Homo sapiens', 'H. sapiens', 'Hs', 'human', 'man'], 'taxId': '9606', 'abbreviation': 'HSA', 'className': 'Species', 'schemaClass': 'Species'}]
  - summation: [{'dbId': 2142849, 'displayName': 'Hyaluronan (hyaluronic acid, hyaluronate or HA) is an anioni...', 'text': 'Hyaluronan (hyaluronic acid, hyaluronate or HA) is an anionic glycosaminoglycan (GAG) distributed widely throughout connective, epithelial, and neural tissues and most abundant in the extracellular matrix and skin. HA is unique among the GAGs in that it is not sulfated and is not found covalently attached to proteins as a proteoglycan. HA polymers are very large (they can reach molecular weights of 10 million Da) and can displace a large volume of water making them excellent lubricators and shock absorbers. Another unique feature of HA is that it is synthesized at the plasma membrane unlike other GAGs which are formed in the Golgi. HA is a polymer of the disaccharide unit  D-glucuronic acid and D-N-acetylglucosamine, linked via alternating beta-1,4 and beta-1,3 glycosidic bonds (Toole 2000, 2004, Volpi et al. 2009).', 'className': 'Summation', 'schemaClass': 'Summation'}]
  - reviewStatus: {'dbId': 9821382, 'displayName': 'five stars', 'definition': 'externally reviewed', 'name': ['five stars'], 'className': 'ReviewStatus', 'schemaClass': 'ReviewStatus'}
  - hasDiagram: False
  - hasEHLD: False
  - hasEvent: [{'dbId': 2142850, 'displayName': 'Hyaluronan biosynthesis and export', 'stId': 'R-HSA-2142850', 'stIdVersion': 'R-HSA-2142850.3', 'isInDisease': False, 'isInferred': False, 'name': ['Hyaluronan biosynthesis and export'], 'releaseDate': '2012-06-12', 'speciesName': 'Homo sapiens', 'hasDiagram': False, 'hasEHLD': False, 'className': 'Pathway', 'schemaClass': 'Pathway'}, {'dbId': 2160916, 'displayName': 'Hyaluronan uptake and degradation', 'stId': 'R-HSA-2160916', 'stIdVersion': 'R-HSA-2160916.4', 'isInDisease': False, 'isInferred': False, 'name': ['Hyaluronan uptake and degradation'], 'releaseDate': '2012-06-12', 'speciesName': 'Homo sapiens', 'hasDiagram': False, 'hasEHLD': False, 'className': 'Pathway', 'schemaClass': 'Pathway'}]
  - className: Pathway
  - schemaClass: Pathway
- relations:
  parent-child: {pathway: (Glycosaminoglycan metabolism, Hyaluronan biosynthesis and export, Hyaluronan uptake and degradation),}